### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Goldeneye128/goldenprompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by Goldeneye128** [comment]
Okay so you want to have a screenshot of how this look like? well guess i can add that if thats what you want? This is just a super simple zsh prompt that simplify stuff for me. If others want to use this i guess i would have to make a more template version of this.

**Comment by Goldeneye128** [comment]
Hey so i redid a few things so its more friendly for anyone who wanna use this. And i added a screenshot. Hope this was all you wanted. Closing this issue as its done.
